name = "Piccoli_Padua_Martinez_2025"
uuid = "c6b3f0f8-e897-4e13-8cad-643a54663e5d"
authors = ["viniciuspiccoli <viniciuspiccoli2008@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
